### ISSUE TITLE
What version of Delphi this is ?

### ISSUE THREAD

**Issue by nissimzur** [nodemcu/nodemcu-flasher#14]
My Delphi is very old. What version of Delphi this project is compiled with ? (16. 17.2 ..)
Can you offer the URL link to downloading it ? 
Thank you
-Nissim

**Comment by vowstar** [comment]
We are using RAD Studio XE8,
http://altd.embarcadero.com/download/radstudio/xe8/delphicbuilder_xe8_upd1_subscription.iso

**Comment by nissimzur** [comment]
Thank you
