### ISSUE TITLE
Tool doesn't work on win10-64bit

### ISSUE THREAD

**Issue by MishraShivendra** [nodemcu/nodemcu-flasher#20]
I tried to run this tool on windows 10 - 64 and it doesn't run. Sometimes, It gives an error "App is incompatible."

**Comment by sihui62** [comment]
Cannot confirm that: works fine on my W10 64Bit.

**Comment by gourneau** [comment]
As of today the tool worked fine for me with Windows 10 64bit.

**Comment by gtsoftwareltd** [comment]
I just tried this on Windows 10 64-bit and I can confirm that the flasher does work.

One thing I have seen is that people just download the flasher exe and end up with a small file (about 44KB) that is actually a HTML page. This can happen by right clicking on the exe and choosing to 'save link as'; this isn't what you want. Download the whole Zip (or clone) and then run the 6MB exe.

**Comment by bubba198** [comment]
r-click and "run as administrator" -- that's at least my experience since my user account apparently doesn't have local administrator rights (Microsoft term lol)

**Comment by Sygyzmundovych** [comment]
![win10_64bit_flasher](https://cloud.githubusercontent.com/assets/8822534/20042209/31762dd2-a476-11e6-80ef-bbaa521a5c8c.png)
Got this on Win10 64bit running as Administrator

**Comment by Imperativ** [comment]
> One thing I have seen is that people just download the flasher exe and end up with a small file (about 44KB) that is actually a HTML page. This can happen by right clicking on the exe and choosing to 'save link as'; this isn't what you want. Download the whole Zip (or clone) and then run the 6MB exe.


It's exactly that. Thanks for the tipp. Maybe someone could publish this info more prominent...and not in a small threat under closed issues...
