### ISSUE TITLE
Broken image links in ReadMe 

### ISSUE THREAD

**Issue by robinkam** [nodemcu/nodemcu-flasher#32]
Please fix the broken image links in the ReadMe document for new comers like me to get better instructions from the document. Thanks a lot!
<img width="815" alt="broken-image-link" src="https://user-images.githubusercontent.com/1436124/28397465-46fd2890-6d34-11e7-988c-24e290f09587.png">

**Comment by jshnaidman** [comment]
There's essentially no instructions available since the photos became unavailable!

**Comment by RH2** [comment]
Yes, please fix.

**Comment by vowstar** [comment]
Fixed
