### ISSUE TITLE
Baud rate issue

### ISSUE THREAD

**Issue by jm01alternet** [nodemcu/nodemcu-flasher#5]
The program seems to ignore the user baud rate setting..

Shouldn't the line in UnitFormMain.pas (around line 1004)

    if (ComboBoxFlashBaudrate.Text = '') then

be

    if (ComboBoxFlashBaudrate.Text <> '') then

Thanks for your great work

**Comment by vowstar** [comment]
Yes, It is a bug. Very thanks your suggestion, I will fix it.
